
---
deployment:
  tasks:
    # 1. Clear any previous build artifacts in the source directory's public folder
    - export DEPLOYPATH=/home4/therac29/public_html/HUGO_SITES/POINTER_ABC/public
    # - rm -rf ../public
    # - mkdir ../public
    - /usr/bin/rsync -avz --delete public/ $DEPLOYPATH/